### ISSUE TITLE
Attaching to Chrome no longer works

### ISSUE THREAD

**Issue by jtidwe11** [octref/vscode-electron-debug#10]
Following the instructions given no longer works for launching with Chrome.  Using current version of Debugger for Chrome / VS Code and electron 1.5.1, as declared in package.json.  Using latest electron has no effect.

Didn't change any of the files, only added breakpoints just to verify that this solution was indeed working.

Something change here that additionally needs to be done?  localhost in browser has json data, so I assume the debugger is working correctly?

Using Non ES6 project.

ES6 version doesn't work either, fwiw.

**Comment by ahmadhadidi** [comment]
Were you able to attach the debugger?

**Comment by octref** [comment]
Both versions still work for me w/ Electron 1.5.1 and VS Code 1.17.

Sorry somehow I didn't see this issue for very long. If this is still an issue, let me know your platform, Electron / VS Code version and I can take a look.
