### ISSUE TITLE
app.getName and app.getPath('userData') return wrong result !

### ISSUE THREAD

**Issue by fomenyesu** [octref/vscode-electron-debug#11]
app.getName and app.getPath('userData') return wrong result in vscode debug mode.
It turn's out app.getName return 'Electron' and app.getPath('userData') return '.../.../Aplication Support/Electron'.

**Comment by octref** [comment]
You can report that to VSCode. However `app.getName` returning `Electron` sounds right.

**Comment by fomenyesu** [comment]
I got the name 'el-work' when I run dev mode & product mode.
'el-work' was configed in my package.json.
But in debug mode it returns 'Electron'.

**Comment by octref** [comment]
Yeah, then that's a VSCode problem with its debug mode. Open an issue at https://github.com/Microsoft/vscode/issues/new
