### ISSUE TITLE
Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: Parse Error)

### ISSUE THREAD

**Issue by rudyxu1102** [octref/vscode-electron-debug#13]
- VSCode Version: 1.19.1
- OS Version: Windows 7 Pro 64 bits
- NodeJs Version: 8.1.4
 
Because the error of `Cannot connect to runtime via 'legacy' protocol; consider using 'inspector' protocol (timeout after 10000 ms)`, I set the "protocol" attribute to "inspector" instead of "legacy"

And then, I catch the error of `Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: Parse Error)`

I have no idea about this.

Can you help me please with this issue ?

Thank you for your answers..

**Comment by octref** [comment]
I suggest you follow this new guide if you are using inspector protocol: https://github.com/Microsoft/vscode-recipes/tree/master/Electron

**Comment by octref** [comment]
I'll update the blog post and the code later.
