### ISSUE TITLE
runtimeExecutable does not exist

### ISSUE THREAD

**Issue by alexistbell** [octref/vscode-electron-debug#15]
I cloned this repo to try and get VScode's debugger working with an electron app. I've made sure to run yarn to get all the node_modules installed (in both the es6 and the other version of the project, just in case). But when I try to run the debugger in VScode I get this error:

Attribute 'runtimeExecutable' does not exist ('/Users/alexisbell/Documents/Electron/vscode-electron-debug/node_modules/.bin/electron').

My launch.json looks like this:

```
{
    "version": "0.2.0",
    "configurations": [
      {
        "name": "Debug Main Process",
        "type": "node",
        "request": "launch",
        "cwd": "${workspaceRoot}",
        "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
        "windows": {
          "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"
        },
        "program": "${workspaceRoot}/main.js",
        "protocol": "inspector",
      }
    ]
  }
```

If it makes any sort of difference, I'm running VScode 1.33.0 on a Mac.

**Comment by octref** [comment]
Does your folder structure look like this?

```
 vscode-electron-debug > tree -L 2
.
├── README.md
├── electron-quick-start
│   ├── node_modules/
├── electron-quick-start-es6
│   ├── node_modules/
```

As you see, `.bin/electron` only exists in one of `electron-quick-start` or `electron-quick-start-es6`, but doesn't exist in `vscode-electron-debug/node_modules`.

**Comment by alexistbell** [comment]
Thanks so much. Yes the file path was the issue. Hopefully this will also work for me in my own project that it having similar issues.
