### ISSUE TITLE
"type": "chrome" not supported

### ISSUE THREAD

**Issue by kakyoism** [octref/vscode-electron-debug#18]
Thanks for this nice repo. It helped me a lot for setting up VSCode for my Electron project.
However, my VSCode lint complains about `"type": "chrome"` field of the "Debug Renderer Process" config, saying that it's an unrecognized option.

I've been having trouble finding the list of available options for the `type` field in the official VSCode doc. 
Do you know how to fix this?

Thanks!

**Comment by octref** [comment]
You need to install https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome.
