### ISSUE TITLE
Source map expected behavior

### ISSUE THREAD

**Issue by aolney** [octref/vscode-electron-debug#2]
Thanks for this tutorial :)

Currently I can set breakpoints in js, start debugging, and the breakpoint triggers on the correct line of f#.

However I can't do the reverse (set breakpoint in f# and trigger on the correct line of js) and the views are not synchronized (ideally stepping through would advance through matching lines in the f# and the js).

Is my current behavior the way that source maps are supposed to work, or is there something I can do to get the functionality above?

**Comment by octref** [comment]
Are you compiling F# to JS, and then use `node` to launch the compiled JS?

Would be helpful if you can give me a sample project with all deps (hello world is fine). I'm not at all familiar with F#.

**Comment by aolney** [comment]
Thanks for your interest. I've made a [hello world application](https://github.com/aolney/fable-electron-vscode-debug-helloworld).

The steps I'm following are in the vscode portion of the readme. I'm using a fable build task from vscode and then using one of your debug tasks to run the compiled js.

I haven't used vscode before, so it's not clear to me if this is how source maps are supposed to work in vscode, and specifically when using vscode to debug electron.

I've seen tutorials with screenshots showing side by side windows of source and transpiled in a debug session, but it's not clear if those views are synchronized by vscode or if people just manually scroll one of the windows.

**Comment by octref** [comment]
The thing is, Chrome Debugger does not enable debugging for fsharp files:

https://github.com/Microsoft/vscode-chrome-debug/blob/3e2e4c4a66fc895fecae1f23f24f9b5617bb8c53/package.json#L53-L58

The hacky way is to go to your `~/.vscode-insiders/extensions/msjsdiag.debugger-for-chrome-1.0.0` (remove the insider part if you are using stable), find `package.json`, and add this line:

![image](https://cloud.githubusercontent.com/assets/4033249/19131550/b722a57c-8b04-11e6-8f9b-370fab0dc52f.png)

Then launch your project. Here you can see me debugging fsx file.

![f](https://cloud.githubusercontent.com/assets/4033249/19131630/0d899006-8b05-11e6-9fa6-7c4be1bda8a5.gif)

**Comment by octref** [comment]
Renderer works too:
![image](https://cloud.githubusercontent.com/assets/4033249/19131753/87fc3fe6-8b05-11e6-8553-5ac4add42e32.png)

**Comment by octref** [comment]
I made a PR against your repo, this is the correct way to setup electron:

https://github.com/aolney/fable-electron-vscode-debug-helloworld/pull/1

**Comment by octref** [comment]
As this solution is hacky, I opened this issue to get some feedback from Chrome Debugger side as to what's the best way to do it: https://github.com/Microsoft/vscode-chrome-debug/issues/240

**Comment by octref** [comment]
F# is added to Chrome Debugger: https://github.com/Microsoft/vscode-chrome-debug/commit/4787fc3d888007b5dc02c75182e48c88b39fc2dc

You can see it in next release. Before that just manually edit the `package.json` should work.

**Comment by aolney** [comment]
Thanks!
