### ISSUE TITLE
Interested in turning this into a real vscode debugger?

### ISSUE THREAD

**Issue by auchenberg** [octref/vscode-electron-debug#3]
Here at Microsoft has architected our chrome-family of debuggers for VS Code to use a core library called [vscode-chrome-debug-core](https://github.com/Microsoft/vscode-chrome-debug-core).

This core library could be used in a new `vscode-electron-debug` debugger that contained the Electron specific configuration parameters, etc, which overall could enable a `launch.json` config like:

``` js
    {
      "name": "Electron debug",
      "type": "electron",
      "request": "launch",
      "main": "${workspaceRoot}/main.js",
      "debugTarget": "renderer" // renderer or main,
      "webRoot": "${workspaceRoot}"
    }
```

We already have a [debugger for iOS](https://github.com/Microsoft/vscode-ios-web-debug) that's architected in a similar way, and I'm thinking it could be awesome to see a dedicated debugger for Electron.

**Comment by octref** [comment]
Sure, that sounds awesome. Thanks for letting me know `vscode-chrome-debug-core`.
I'll try to build a prototype this weekend.

**Comment by weinand** [comment]
The node version built into Electron does not support the Chrome Debugging protocol (yet), so the core library mentioned above does not help.

But this is not an issue because the VS Code node debugger has always supported Electron (because VS Code is based on Electron and we are selfhosting on the VS Code node debugger).

And we have an Intellisense snippet for easily adding a launch config for Electron in the next Insider build.

**Comment by octref** [comment]
@weinand Sounds great. Maybe also add `"type": "electron"` which defaults to legacy protocol, etc, doing all the setup so user only need to specify entry point and which of main/renderer to debug?

**Comment by weinand** [comment]
@octref Every new "type" shows up as a separate debugger environment in VS Code and it duplicates all meta information about attributes etc. It is a very heavyweight way to introduce a new launch config with some predefined attributes. I suggest that we keep the number of debug types small and do not introduce new types that are just aliases for a base type (here 'node').
 
In the January milestone we have introduced Intellisense snippets to cover different setup scenarios for node debugging, e.g. "gulp", "yeoman", "typescript", "remote debugging". I suggest that we support the electron setup by a new snippet "Electron Main Process".

**Comment by octref** [comment]
I feel debugging renderer is of more use, but still +1 for adding IntelliSense to debugging main process.

**Comment by weinand** [comment]
Sure, for debugging the renderer I've asked @roblourens to create an IntelliSense snippet for the chrome debugger (see https://github.com/Microsoft/vscode-chrome-debug/issues/354).

**Comment by roblourens** [comment]
I've thought that we should keep the "one extension per runtime" principle and have someone maintain a separate extension for electron debugging. I just think that a dedicated extension can provide a better experience, since it has its own issues, and I won't be testing with electron regularly.

**Comment by auchenberg** [comment]
I second @roblourens, and this is the reason for why I opened this issue in the first place. Going forward Electron might need addtional launch params, etc

**Comment by octref** [comment]
OK I'll give it a try, this isn't top on my list as I'm working on another extension, but I'll try to get a basic one before next month's release.
