### ISSUE TITLE
¿console.log in renderer process?

### ISSUE THREAD

**Issue by sant123** [octref/vscode-electron-debug#4]
Hi, when using the renderer process ¿where is the output from the `console.log`? I looked up in the "DEBUG CONSOLE" of VS Code, the developer tools and the Node.js terminal but nothing appears.

Thanks.

![image](https://cloud.githubusercontent.com/assets/7959437/19732925/05af2f58-9b68-11e6-9373-43a47411fc2c.png)

**Comment by octref** [comment]
Chrome Debugger issue, tracked at https://github.com/Microsoft/vscode-chrome-debug/issues/271

Meanwhile, you can try downloading this zip file (1.2.1 version which doesn't have this bug), and open it from here:

![image](https://cloud.githubusercontent.com/assets/4033249/19736792/a3aa1d4c-9b65-11e6-80fb-db06a099c8af.png)

[debugger-for-chrome-1.2.1.vsix.zip](https://github.com/octref/vscode-electron-debug/files/554008/debugger-for-chrome-1.2.1.vsix.zip)
