### ISSUE TITLE
Source map problem while debugging renderer

### ISSUE THREAD

**Issue by davidka** [octref/vscode-electron-debug#5]
I followed the guide to debug the renderer process but unfortunately got the following message on my breakpoints in renderer.js:

`Breakpoint ignored because generated code not found (source map problem?).`

Here is my environment:
VSCode 1.8.1
Debugger for Chrome 2.4.2
macOS 10.12.2

**Comment by davidka** [comment]
Just tried it out on windows 10 and it works. Seems to be a problem on mac

**Comment by octref** [comment]
I remember they recently changed the format of specifying sourcemap. Can you try adding `outFiles` pointing to your transpiled code?

Also, you are using webpack 1 right?

**Comment by davidka** [comment]
Great ist works with "outFiles", although vscode shows a warning: Property outFiles is not allowed
