### ISSUE TITLE
no call stack available (Internal error: TypeError: undefined is not a function

### ISSUE THREAD

**Issue by ghost** [octref/vscode-electron-debug#7]
i have downed the vscode-electron-debug project ,and npm installed all the dependecies,but it report 
no call stack available (Internal error: TypeError: undefined is not a function), f5 can run the app，but no stop on the breakpoint

**Comment by octref** [comment]
Can you post a screenshot?

**Comment by octref** [comment]
Reopen if you can provide more details. Thanks.
