### ISSUE TITLE
Can't get debugging to work correctly.

### ISSUE THREAD

**Issue by bangclash** [octref/vscode-electron-debug#8]
I'm new to electron and download the electron quickstart project to test debugging. I have the same launch.json as your example. I added a breakpoint in the main.js file. When I launch the app it seems to stop at the break point but in code window it doesn't show that it's stopped at the break point. I think it's at the breakpoint because the app is paused until I hit the continue button. I'm using visual studio code 1.10.2 on windows 10. I was wondering if you have that problem?

**Comment by octref** [comment]
Can you post a screenshot? I don't quite understand what's happening.

**Comment by bangclash** [comment]
I've launch debugger. You can see I have a breakpoint at line 38. I think it's hit that breakpoint at line 38 because the debug console shows "hello" but not "world". The code window doesn't show it's stopped at line 38 but the program is currently paused. Then I do continue (F5) then I will see "world" in the debug console. It seems like it hits the breakpoint but code window doesn't reflect it. Plus there is also error in the call stack. I hope this was clearer. Thank you.

![screenshotvs](https://cloud.githubusercontent.com/assets/10566143/23828576/2c8c45d2-068b-11e7-999b-7d0d9387b5bb.png)

**Comment by octref** [comment]
Good catch. I think it's a regression in VSCode. Opened an issue for you:
https://github.com/Microsoft/vscode/issues/22466

It's also not working for me right now.

**Comment by bangclash** [comment]
Thank you for opening the issue for me. I thought I was going crazy.

**Comment by bangclash** [comment]
Accidently closed issue. Want to leave this open as a reference for https://github.com/Microsoft/vscode/issues/22466

**Comment by octref** [comment]
See https://github.com/Microsoft/vscode/issues/22015.

Use Electron 1.5.1 for now.
