### ISSUE TITLE
Getting an error when trying to debug Electron

### ISSUE THREAD

**Issue by Hum4n01d** [octref/vscode-electron-debug#9]
Hi! I’m trying to debug my Electron app in VSCode and I stumbled upon your post about it but neither this post or any other one I can find has worked for me. Would you mind trying to help me? My error is:

```
App threw an error during load
Error: Cannot find module '/Users/Hum4n01d/Desktop/Tech/Electron/Amango/—debug-brk=18666'
```

There is more information here: http://stackoverflow.com/q/43313689/7438201

**Comment by octref** [comment]
Did you clone this repo, run it and is getting the same error?
I didn't see any `.vscode` folder in your repo, like this one: https://github.com/octref/vscode-electron-debug/tree/master/electron-quick-start/.vscode

**Comment by wuscier** [comment]
When I cloned your repository and did like the instruction, it worked well and I was able to hit the breakpoints. But then an error occurred,  `#
# Fatal error in c:\jenkins\workspace\libchromiumcontent-win\src\v8\src\runtime\runtime-debug.cc, line 1423
# Check failed: args[0]->IsJSObject().
#

==== C stack trace ===============================

	icu_56::FieldPositionHandler::shiftLast [0x00007FF9FDA532EB+1135]
	ucache_hashKeys_56 [0x00007FF9FD806769+26793]
	ucache_hashKeys_56 [0x00007FF9FD8AF531+718449]
	(No symbol) [0x000001DD49C063AB]
`
It seemed that it timed out.

**Comment by Hum4n01d** [comment]
I would use 'electron-forge' if I were you @wucier. I opened some issues and talked to the author and they built a special CLI for VSCode.

**Comment by Hum4n01d** [comment]
See this for more: https://github.com/electron-userland/electron-forge/blob/master/README.md#debugging-your-application-through-vs-code

**Comment by wuscier** [comment]
Great to know 'electron-forge'. I'm new to electron. Thanks for helping.
